### ISSUE TITLE
Update Faculty Directory Poster

### ISSUE THREAD

**Issue by ejcrowe** [dahous1/UMBC-Physics#10]
- [x] Erik Send David GIMP files for Poster
- [x] Update Titles for numerous Faculty Members (Check the website, It is up to date)
- [x] Remove Dr. Turner from the Emeritus List
- [x] Add Xiaoguang (Richard) Xu;  Research Assistant Professor to the affiliated list
- [x] Get Picture of Richard (Erik emailed Jen)
- [x] Look to see if they make LED replacements for the Fluorescent Bulbs in the Cabinet

**Comment by dahous1** [comment]
I have made the changes to the document. Did you want to double check to make sure everything is kosher? I also looked into replacement bulbs. There are LED versions of those kind, just need to check the wattage.

**Comment by ejcrowe** [comment]
@dahous1 Is the Poster ready to print?

**Comment by dahous1** [comment]
Yes
