### ISSUE TITLE
Create Master List for Building Occupants

### ISSUE THREAD

**Issue by ejcrowe** [dahous1/UMBC-Physics#5]
- [x] 1.  Create Spreadsheet from Dr. Gougousi's Document
- [x] 2.  Verify List by walking the building
- [x] 3.  Update Door Placards
- [x] 4.  Request New Door Placards
- [x] 5.  Replace Label on Siemens Door

**Comment by dahous1** [comment]
Test comment

**Comment by ejcrowe** [comment]
[Building Occupancy List.xlsx](https://github.com/dahous1/UMBC-Physics/files/7039573/Building.Occupancy.List.xlsx)

**Comment by ejcrowe** [comment]
@dahous1 This is the master list that I made from walking the building.  Can you check the following:

- [ ] Yellow Highlighted on the spreadsheet except for Vacant
- [ ] Yellow Indicates we might need a label added to the placard
- [ ] Check to see if Siemens is in PHYS 017, if not make update spreadsheet
- [ ] Attach Updated Spreadsheet when you are finished
- [ ] Send this list to Jen Salmi

**Comment by ejcrowe** [comment]
@dahous1 Please update Siemens Door Label for uniformity.  Did you ever hear back about new door placards?
