### ISSUE TITLE
Overflow for PHYS 401

### ISSUE THREAD

**Issue by ejcrowe** [dahous1/UMBC-Physics#7]
- [x] 1. Order Correct Cabling (HDMI, Aux, etc...)
- [x] 2. Placement of Camera
- [x] 3. Test Audio in PHYS 401 & PHYS 226
- [x] Add instructions in 226 and 401 on how to use equipment.
- [x] Organize cabling

**Comment by ejcrowe** [comment]
@dahous1 Did the Cables Arrive?

**Comment by dahous1** [comment]
- [ ] Submit ticket with IT to activate ethernet ports
- [ ] confirm ethernet works
- [ ] confirm webex works
